Repository UMC-Mini/UMC-Mini-Project-BackEnd, pull requests merged in 2024-06, with the labels that each got.

#3 ✨ [Feat] 에러 핸들러, 응답 통일, 스웨거 설정, Dockerfile 추가 및 yml, build 파일 수정
  Dockerfile
  build.gradle
  src/main/java/com/miniproject/demo/global/config/SwaggerConfig.java
  src/main/java/com/miniproject/demo/global/error/exception/ExceptionAdvice.java
  src/main/java/com/miniproject/demo/global/error/exception/GeneralException.java
  src/main/java/com/miniproject/demo/global/error/handler/TestHandler.java
  src/main/java/com/miniproject/demo/global/response/BaseResponse.java
  src/main/java/com/miniproject/demo/global/response/code/BaseCode.java
  src/main/java/com/miniproject/demo/global/response/code/BaseErrorCode.java
  src/main/java/com/miniproject/demo/global/response/code/ErrorReasonDTO.java
  src/main/java/com/miniproject/demo/global/response/code/ReasonDTO.java
  src/main/java/com/miniproject/demo/global/response/code/status/ErrorStatus.java
  src/main/java/com/miniproject/demo/global/response/code/status/SuccessStatus.java
  src/main/resources/application.yml
Labels: ✨ Feature

#5 Create CI/CD
  .github/workflows/gradle.yml
Labels: 🏗 Infra

#9 :sparkles: [FEAT] User 도메인 관련 엔티티 개발
  src/main/java/com/miniproject/demo/domain/account/entity/User.java
  src/main/java/com/miniproject/demo/domain/chatbot/entity/ChatBotRoom.java
  src/main/java/com/miniproject/demo/domain/mapping/UserChatRoom.java
  src/main/java/com/miniproject/demo/domain/post/entity/Post.java
  src/main/java/com/miniproject/demo/global/response/code/BaseEntity.java
Labels: ✨ Feature

#12 ✨[Feat] Post, Reply CRUD, Pagination 구현, git workflow 수정
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  src/main/java/com/miniproject/demo/SmupoolApplication.java
  src/main/java/com/miniproject/demo/domain/post/controller/PostController.java
  src/main/java/com/miniproject/demo/domain/post/converter/PostConverter.java
  src/main/java/com/miniproject/demo/domain/post/domain/Post.java
  src/main/java/com/miniproject/demo/domain/post/dto/PostRequestDTO.java
  src/main/java/com/miniproject/demo/domain/post/dto/PostResponseDTO.java
  src/main/java/com/miniproject/demo/domain/post/repository/PostRepository.java
  src/main/java/com/miniproject/demo/domain/post/service/PostService.java
  src/main/java/com/miniproject/demo/domain/post/service/PostServiceImpl.java
  src/main/java/com/miniproject/demo/domain/post/validation/annotation/ExistPost.java
  src/main/java/com/miniproject/demo/domain/post/validation/validator/PostExistValidator.java
  src/main/java/com/miniproject/demo/domain/reply/controller/ReplyController.java
  src/main/java/com/miniproject/demo/domain/reply/converter/ReplyConverter.java
  src/main/java/com/miniproject/demo/domain/reply/domain/Reply.java
  src/main/java/com/miniproject/demo/domain/reply/dto/ReplyRequestDTO.java
  src/main/java/com/miniproject/demo/domain/reply/dto/ReplyResponseDTO.java
  src/main/java/com/miniproject/demo/domain/reply/repository/ReplyRepository.java
  src/main/java/com/miniproject/demo/domain/reply/service/ReplyService.java
  src/main/java/com/miniproject/demo/domain/reply/service/ReplyServiceImpl.java
  src/main/java/com/miniproject/demo/domain/reply/validation/annotation/ExistReply.java
  src/main/java/com/miniproject/demo/domain/reply/validation/validator/ReplyExistValidator.java
  src/main/java/com/miniproject/demo/global/error/handler/PostHandler.java
  src/main/java/com/miniproject/demo/global/error/handler/ReplyHandler.java
  src/main/java/com/miniproject/demo/global/response/code/status/ErrorStatus.java
  src/test/java/com/miniproject/demo/domain/post/service/PostServiceTest.java
  src/test/java/com/miniproject/demo/domain/reply/service/ReplyServiceTest.java
Labels: ✨ Feature

#13 Feat/#10 채팅방, 채팅 엔티티 구현 및 연관관계 매핑
  src/main/java/com/miniproject/demo/domain/chatroom/entity/ChatMessage.java
  src/main/java/com/miniproject/demo/domain/chatroom/entity/Chatroom.java
  src/main/java/com/miniproject/demo/domain/mapping/UserChatRoom.java
Labels: ✨ Feature

#15 ✨[Feat] USER CUD 구현, 디렉토리 구조 수정
  .gradle/8.7/executionHistory/executionHistory.lock
  .gradle/8.7/fileHashes/fileHashes.lock
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  build.gradle
  src/main/java/com/miniproject/demo/domain/account/controller/UserController.java
  src/main/java/com/miniproject/demo/domain/account/converter/UserConverter.java
  src/main/java/com/miniproject/demo/domain/account/dto/CustomUserDetails.java
  src/main/java/com/miniproject/demo/domain/account/dto/LoginRequestDTO.java
  src/main/java/com/miniproject/demo/domain/account/dto/LoginResponseDTO.java
  src/main/java/com/miniproject/demo/domain/account/dto/UserRequestDTO.java
  src/main/java/com/miniproject/demo/domain/account/dto/UserResponseDTO.java
  src/main/java/com/miniproject/demo/domain/account/entity/User.java
  src/main/java/com/miniproject/demo/domain/account/repository/UserRepository.java
  src/main/java/com/miniproject/demo/domain/account/service/UserService.java
  src/main/java/com/miniproject/demo/domain/account/service/UserServiceImpl.java
  src/main/java/com/miniproject/demo/domain/chatroom/entity/ChatMessage.java
  src/main/java/com/miniproject/demo/domain/post/controller/PostController.java
  src/main/java/com/miniproject/demo/domain/post/converter/PostConverter.java
  src/main/java/com/miniproject/demo/domain/post/domain/Post.java
  src/main/java/com/miniproject/demo/domain/post/entity/Post.java
  src/main/java/com/miniproject/demo/domain/post/repository/PostRepository.java
  src/main/java/com/miniproject/demo/domain/post/service/PostService.java
  src/main/java/com/miniproject/demo/domain/post/service/PostServiceImpl.java
  src/main/java/com/miniproject/demo/domain/reply/domain/Reply.java
  src/main/java/com/miniproject/demo/domain/reply/repository/ReplyRepository.java
  src/main/java/com/miniproject/demo/domain/reply/service/ReplyServiceImpl.java
  src/main/java/com/miniproject/demo/global/config/PrincipalDetails.java
  src/main/java/com/miniproject/demo/global/config/PrincipalDetailsService.java
  src/main/java/com/miniproject/demo/global/config/SecurityConfig.java
  src/main/java/com/miniproject/demo/global/config/SwaggerConfig.java
  src/main/java/com/miniproject/demo/global/config/filter/JWTAccessDeniedHandler.java
  src/main/java/com/miniproject/demo/global/config/filter/JWTAuthenticationEntryPoint.java
  src/main/java/com/miniproject/demo/global/config/filter/JWTExceptionFilter.java
  src/main/java/com/miniproject/demo/global/config/filter/JWTFilter.java
  src/main/java/com/miniproject/demo/global/config/filter/LoginFilter.java
  src/main/java/com/miniproject/demo/global/config/jwt/JWTUtil.java
  src/main/java/com/miniproject/demo/global/error/handler/AuthHandler.java
  src/main/java/com/miniproject/demo/global/error/handler/UserHandler.java
  src/main/java/com/miniproject/demo/global/response/code/status/ErrorStatus.java
  src/main/resources/application.yml
  src/test/java/com/miniproject/demo/domain/post/service/PostServiceTest.java
  src/test/java/com/miniproject/demo/domain/reply/service/ReplyServiceTest.java
Labels: ✨ Feature

#17 ✨ [Feat] 게시글 유저 매핑 및 게시글 비밀번호 추가 및 댓글 응답 변경
  build.gradle
  src/main/java/com/miniproject/demo/domain/account/entity/User.java
  src/main/java/com/miniproject/demo/domain/account/service/UserServiceImpl.java
  src/main/java/com/miniproject/demo/domain/chatbot/entity/ChatBotRoom.java
  src/main/java/com/miniproject/demo/domain/chatroom/entity/Chatroom.java
  src/main/java/com/miniproject/demo/domain/post/controller/PostController.java
  src/main/java/com/miniproject/demo/domain/post/converter/PostConverter.java
  src/main/java/com/miniproject/demo/domain/post/dto/PostRequestDTO.java
  src/main/java/com/miniproject/demo/domain/post/dto/PostResponseDTO.java
  src/main/java/com/miniproject/demo/domain/post/entity/Post.java
  src/main/java/com/miniproject/demo/domain/post/repository/PostRepository.java
  src/main/java/com/miniproject/demo/domain/post/service/PostService.java
  src/main/java/com/miniproject/demo/domain/post/service/PostServiceImpl.java
  src/main/java/com/miniproject/demo/domain/reply/controller/ReplyController.java
  src/main/java/com/miniproject/demo/domain/reply/converter/ReplyConverter.java
  src/main/java/com/miniproject/demo/domain/reply/domain/Reply.java
  src/main/java/com/miniproject/demo/domain/reply/dto/ReplyResponseDTO.java
  src/main/java/com/miniproject/demo/domain/reply/service/ReplyService.java
  src/main/java/com/miniproject/demo/domain/reply/service/ReplyServiceImpl.java
  src/main/java/com/miniproject/demo/global/config/SecurityConfig.java
  src/main/java/com/miniproject/demo/global/response/code/status/ErrorStatus.java
  src/main/resources/application.yml
  src/test/java/com/miniproject/demo/domain/post/service/PostServiceTest.java
  src/test/java/com/miniproject/demo/domain/reply/service/ReplyServiceTest.java
Labels: ✨ Feature

#18 Feat/#14 채팅방 생성 및 조회, 채팅 유저 조회
  .gradle/8.7/fileHashes/fileHashes.lock
  src/main/java/com/miniproject/demo/domain/chatroom/controller/ChatController.java
  src/main/java/com/miniproject/demo/domain/chatroom/dto/ChatMessageDTO.java
  src/main/java/com/miniproject/demo/domain/chatroom/dto/ChatRoomDTO.java
  src/main/java/com/miniproject/demo/domain/chatroom/entity/ChatMessage.java
  src/main/java/com/miniproject/demo/domain/chatroom/entity/Chatroom.java
  src/main/java/com/miniproject/demo/domain/chatroom/repository/ChatMessageRepository.java
  src/main/java/com/miniproject/demo/domain/chatroom/repository/ChatRoomRepository.java
  src/main/java/com/miniproject/demo/domain/chatroom/service/ChatService.java
  src/main/java/com/miniproject/demo/domain/chatroom/service/ChatServiceImpl.java
  src/main/java/com/miniproject/demo/global/config/WebConfig.java
  src/main/java/com/miniproject/demo/global/config/WebSocketConfig.java
Labels: ✨ Feature

#22 🐛 [Fix] 게시글 요청 수정
  src/main/java/com/miniproject/demo/domain/post/controller/PostController.java
  src/main/java/com/miniproject/demo/domain/post/dto/PostRequestDTO.java
  src/main/java/com/miniproject/demo/domain/post/service/PostService.java
  src/main/java/com/miniproject/demo/domain/post/service/PostServiceImpl.java
  src/test/java/com/miniproject/demo/domain/post/service/PostServiceTest.java
Labels: 🐛 BugFix

#23 :recycle: [REFACTORING] LoginResponseDTO 수정 - 프론트 요청사항
  .gitignore
  src/main/java/com/miniproject/demo/domain/account/dto/LoginResponseDTO.java
Labels: ♻️ Refactor

#24 채팅방 유저 입장 및 조회
  .gradle/8.7/executionHistory/executionHistory.lock
  .gradle/8.7/fileHashes/fileHashes.lock
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  src/main/java/com/miniproject/demo/domain/chatroom/controller/ChatController.java
  src/main/java/com/miniproject/demo/domain/chatroom/converter/ChatRoomConverter.java
  src/main/java/com/miniproject/demo/domain/chatroom/dto/ChatJoinRequestDTO.java
  src/main/java/com/miniproject/demo/domain/chatroom/dto/ChatRoomRequestDTO.java
  src/main/java/com/miniproject/demo/domain/chatroom/dto/ChatRoomResponseDTO.java
  src/main/java/com/miniproject/demo/domain/chatroom/entity/Chatroom.java
  src/main/java/com/miniproject/demo/domain/chatroom/repository/UserChatRepository.java
  src/main/java/com/miniproject/demo/domain/chatroom/service/ChatService.java
  src/main/java/com/miniproject/demo/domain/chatroom/service/ChatServiceImpl.java
Labels: ✨ Feature

#27 :recycle: feat: UserUpdate fix
  src/main/java/com/miniproject/demo/domain/account/controller/UserController.java
  src/main/java/com/miniproject/demo/domain/account/entity/User.java
  src/main/java/com/miniproject/demo/domain/account/repository/UserRepository.java
  src/main/java/com/miniproject/demo/domain/account/service/UserService.java
  src/main/java/com/miniproject/demo/domain/account/service/UserServiceImpl.java
  src/main/java/com/miniproject/demo/global/config/SwaggerConfig.java
Labels: ♻️ Refactor

#29 채팅기록 불러오기(유저,컨텐트)
  .gradle/8.7/executionHistory/executionHistory.lock
  .gradle/8.7/fileHashes/fileHashes.lock
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  src/main/java/com/miniproject/demo/domain/chatroom/controller/ChatController.java
  src/main/java/com/miniproject/demo/domain/chatroom/converter/ChatMessageConverter.java
  src/main/java/com/miniproject/demo/domain/chatroom/dto/ChatMessageResponseDTO.java
  src/main/java/com/miniproject/demo/domain/chatroom/entity/ChatMessage.java
  src/main/java/com/miniproject/demo/domain/chatroom/repository/ChatMessageRepository.java
  src/main/java/com/miniproject/demo/domain/chatroom/service/ChatService.java
  src/main/java/com/miniproject/demo/domain/chatroom/service/ChatServiceImpl.java
  src/main/java/com/miniproject/demo/global/config/SecurityConfig.java
  src/main/java/com/miniproject/demo/global/config/WebSocketConfig.java
Labels: ✨ Feature

#33 비밀 채팅방 입장 로직 구현, 웹 소켓 배포
  .gradle/8.7/executionHistory/executionHistory.lock
  .gradle/8.7/fileHashes/fileHashes.lock
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  src/main/java/com/miniproject/demo/domain/chatroom/controller/ChatController.java
  src/main/java/com/miniproject/demo/domain/chatroom/dto/SecretChatJoinRequestDTO.java
  src/main/java/com/miniproject/demo/domain/chatroom/service/ChatService.java
  src/main/java/com/miniproject/demo/domain/chatroom/service/ChatServiceImpl.java
Labels: ✨ Feature

#36 ✨ [Feat] 프로필 api 추가
  src/main/java/com/miniproject/demo/domain/account/controller/UserController.java
  src/main/java/com/miniproject/demo/domain/account/converter/UserConverter.java
  src/main/java/com/miniproject/demo/domain/account/dto/ProfileResponseDTO.java
  src/main/java/com/miniproject/demo/domain/account/service/UserService.java
  src/main/java/com/miniproject/demo/domain/account/service/UserServiceImpl.java
Labels: ✨ Feature

#38 :recycle: [REFACTORING] USER 프로필 제공 수정
  src/main/java/com/miniproject/demo/domain/account/converter/UserConverter.java
  src/main/java/com/miniproject/demo/domain/account/dto/ProfileResponseDTO.java
Labels: ♻️ Refactor
